<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTzO29FO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTzO29FO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTzO29FO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTzO29FO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTzO29FO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TzO29FO',
    'container.build_id' => '27438e25',
    'container.build_time' => 1563527783,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTzO29FO');
